#!/usr/bin/ruby

# better table view for activerecord objects with hirb
begin
  require 'hirb' 
  Hirb.enable
rescue LoadError
  puts "*** hirb disabled ***"  
  puts "gem install hirb"
end

def change_log(stream)
  # send Rails logs to console
  # 2.X
  if ENV.include?('RAILS_ENV') && !Object.const_defined?('RAILS_DEFAULT_LOGGER')
    require 'logger'
    Object.const_set 'RAILS_DEFAULT_LOGGER', Logger.new(stream)
  end
  # 3.X
  ActiveRecord::Base.logger = Logger.new(stream) if defined? Rails::Console
  ActiveRecord::Base.clear_active_connections!
end

def show_log
  change_log(STDOUT)
end

def hide_log
  change_log(nil)
end

def sql(query)
  ActiveRecord::Base.connection.select_all(query)
end

# includes Rails routes helpers
def rails_routes
  include ActionController::UrlWriter
  default_url_options[:host] = 'example.com'
end


