#!/bin/bash

sudo -v
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

source "$HOME"/.templates/provisioning/mac.sh
source "$HOME"/.templates/provisioning/homebrew.sh
source "$HOME"/.templates/provisioning/ruby.sh
source "$HOME"/.templates/provisioning/npm.sh
source "$HOME"/.templates/provisioning/mac-apps.sh
source "$HOME"/.templates/provisioning/fonts.sh
source "$HOME"/.templates/provisioning/vim.sh
source "$HOME"/.templates/provisioning/sublime.sh
