#!/usr/bin/env bash

sudo -v
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

if pkgutil --pkg-info=com.apple.pkg.CLTools_Executables > /dev/null 2>&1; then
  echo "==> Mac OSX Command-Line Tools are installed."
else
  echo "==> Installing Command-Line Tools"
  xcode-select --install
fi

source "$HOME"/.templates/provisioning/mac/osx.sh
source "$HOME"/.templates/provisioning/mac/homebrew.sh
source "$HOME"/.templates/provisioning/ruby.sh
source "$HOME"/.templates/provisioning/npm.sh
source "$HOME"/.templates/provisioning/mac/mac-apps.sh
source "$HOME"/.templates/provisioning/mac/fonts.sh
source "$HOME"/.templates/provisioning/vim.sh
source "$HOME"/.templates/provisioning/emacs.sh
source "$HOME"/.templates/provisioning/sublime.sh

echo "/usr/local/bin/bash" | sudo tee -a /etc/shells
chsh -s /usr/local/bin/bash
