#!/bin/bash

export GIT_AUTHOR_NAME="Allen Bargi"
export GIT_AUTHOR_EMAIL="allen.bargi@gmail.com"
export GITHUB_USERNAME="aziz"

export GIT_COMMITTER_NAME="$GIT_AUTHOR_NAME"
export GIT_COMMITTER_EMAIL="$GIT_AUTHOR_EMAIL"
export NPM_CONFIG_EMAIL="$GIT_AUTHOR_EMAIL"
export NPM_CONFIG_USERNAME="$GITHUB_USERNAME"
export NPM_CONFIG_INIT_AUTHOR_EMAIL="$GIT_AUTHOR_EMAIL"
export NPM_CONFIG_INIT_AUTHOR_NAME="$GIT_AUTHOR_NAME"
export NPM_CONFIG_INIT_AUTHOR_URL="https://github.com/$GITHUB_USERNAME"
