#!/bin/bash

export normal=$'\e[00m'
export reset_color=$'\e[39m'

export black=$'\e[0;30m'
export red=$'\e[0;31m'
export green=$'\e[0;32m'
export yellow=$'\e[0;33m'
export blue=$'\e[0;34m'
export purple=$'\e[0;35m'
export cyan=$'\e[0;36m'
export white=$'\e[1;37m'
export orange=$'\e[33;40m'

export bold_black=$'\e[1;30m'
export bold_red=$'\e[1;31m'
export bold_green=$'\e[1;32m'
export bold_yellow=$'\e[1;33m'
export bold_blue=$'\e[1;34m'
export bold_purple=$'\e[1;35m'
export bold_cyan=$'\e[1;36m'
export bold_white=$'\e[1;37m'
export bold_orange=$'\e[1;33;40m'

export underline_black=$'\e[4;30m'
export underline_red=$'\e[4;31m'
export underline_green=$'\e[4;32m'
export underline_yellow=$'\e[4;33m'
export underline_blue=$'\e[4;34m'
export underline_purple=$'\e[4;35m'
export underline_cyan=$'\e[4;36m'
export underline_white=$'\e[4;37m'
export underline_orange=$'\e[4;33;40m'

export background_black=$'\e[40m'
export background_red=$'\e[41m'
export background_green=$'\e[42m'
export background_yellow=$'\e[43m'
export background_blue=$'\e[44m'
export background_purple=$'\e[45m'
export background_cyan=$'\e[46m'
export background_white=$'\e[47m'
